version: '3.8'

services:
  crm-app:
    # Usar la imagen corregida que usa node server.js directamente
    # en lugar de npm start
    image: pedroconda/crm-probolsas:fixed
    networks:
      - probolsas
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.crm.rule=Host(`ippcrm.probolsas.co`)"
        - "traefik.http.routers.crm.entrypoints=websecure"
        - "traefik.http.routers.crm.tls.certresolver=letsencrypt"
        - "traefik.http.services.crm.loadbalancer.server.port=80"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  probolsas:
    external: true
